In [1]:
import pandas as pd

In [2]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [19]:
sectors.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
...,...,...,...,...,...,...,...
261,Estee Lauder,Household Products,Household and Personal Products,"New York, NY",10780,1089,44000
301,Lennar,Engineering & Construction,Homebuilders,"Miami, FL",9474,803,7749
340,PVH,Apparel,Apparel,"New York, NY",8020,572,26200
354,Ralph Lauren,Apparel,Apparel,"New York, NY",7620,702,20000
448,Hanesbrands,Apparel,Apparel,"Winston-Salem, NC",5732,429,65300

In [3]:
type(sectors)

pandas.core.groupby.generic.DataFrameGroupBy

In [4]:
len(sectors)

21

In [5]:
fortune["Sector"].nunique()

21

In [6]:
sectors.first()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Boeing,Aerospace and Defense,"Chicago, IL",96114,5176,161400
Apparel,Nike,Apparel,"Beaverton, OR",30601,3273,62600
Business Services,ManpowerGroup,Temporary Help,"Milwaukee, WI",19330,419,27000
Chemicals,Dow Chemical,Chemicals,"Midland, MI",48778,7685,49495
Energy,Exxon Mobil,Petroleum Refining,"Irving, TX",246204,16150,75600
Engineering & Construction,Fluor,"Engineering, Construction","Irving, TX",18114,413,38758
Financials,Berkshire Hathaway,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
Food and Drug Stores,CVS Health,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
"Food, Beverages & Tobacco",Archer Daniels Midland,Food Production,"Chicago, IL",67702,1849,32300
Health Care,McKesson,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
"Hotels, Resturants & Leisure",McDonald’s,Food Services,"Oak Brook, IL",25413,4529,420000
Household Products,Procter & Gamble,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
Industrials,General Electric,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
Materials,Alcoa,Metals,"New York, NY",22534,-322,60000
Media,Disney,Entertainment,"Burbank, CA",52465,8382,185000
Motor Vehicles & Parts,General Motors,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
Retailing,Walmart,General Merchandisers,"Bentonville, AR",482130,14694,2300000
Technology,Apple,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
Telecommunications,AT&T,Telecommunications,"Dallas, TX",146801,13345,281450
Transportation,UPS,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
Wholesalers,Sysco,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [7]:
sectors.groups

{'Aerospace & Defense': [24, 45, 60, 88, 118, 120, 209, 245, 282, 378, 389, 490, 560, 605, 785, 788, 836, 903, 958, 987], 'Apparel': [91, 231, 340, 354, 448, 547, 575, 597, 683, 695, 726, 794, 877, 882, 917], 'Business Services': [144, 186, 199, 204, 221, 248, 249, 294, 307, 312, 355, 392, 404, 440, 467, 468, 481, 485, 492, 503, 545, 626, 635, 652, 677, 694, 714, 729, 734, 735, 737, 744, 767, 776, 777, 783, 791, 792, 796, 801, 803, 816, 819, 820, 869, 870, 886, 939, 951, 952, 993], 'Chemicals': [56, 101, 182, 189, 206, 253, 262, 277, 288, 296, 316, 538, 549, 555, 566, 580, 613, 624, 654, 668, 717, 720, 724, 758, 761, 829, 865, 898, 934, 949], 'Energy': [2, 14, 30, 32, 42, 65, 90, 95, 98, 104, 115, 117, 121, 162, 163, 165, 166, 175, 178, 188, 190, 192, 193, 198, 214, 216, 217, 223, 225, 229, 243, 246, 247, 257, 272, 274, 279, 289, 319, 322, 324, 343, 348, 349, 350, 363, 364, 384, 387, 388, 394, 402, 403, 410, 425, 437, 438, 445, 458, 475, 483, 493, 507, 522, 541, 548, 556, 558, 569, 571, 579, 598, 600, 606, 633, 650, 656, 662, 679, 692, 696, 703, 703, 706, 711, 715, 732, 742, 743, 745, 754, 772, 784, 798, 802, 810, 817, 826, 843, 850, ...], 'Engineering & Construction': [155, 156, 235, 260, 301, 314, 352, 381, 433, 478, 498, 501, 516, 572, 576, 640, 719, 738, 822, 863, 874, 892, 929, 963, 985, 994], 'Financials': [4, 16, 23, 26, 27, 29, 35, 40, 43, 49, 50, 61, 69, 73, 74, 76, 78, 81, 82, 83, 85, 100, 105, 112, 114, 131, 135, 137, 152, 171, 179, 184, 205, 210, 222, 226, 227, 232, 236, 250, 252, 259, 264, 265, 271, 273, 275, 283, 298, 306, 311, 318, 326, 329, 332, 344, 347, 367, 368, 376, 382, 398, 401, 411, 421, 436, 442, 449, 453, 453, 471, 472, 472, 476, 479, 482, 486, 488, 494, 497, 499, 506, 509, 510, 520, 529, 531, 536, 540, 551, 561, 568, 573, 590, 603, 609, 611, 646, 651, 663, ...], 'Food and Drug Stores': [7, 17, 19, 87, 107, 160, 181, 595, 614, 631, 669, 756, 809, 849, 928], 'Food, Beverages & Tobacco': [41, 44, 62, 66, 84, 94, 106, 149, 153, 161, 176, 207, 215, 242, 266, 304, 336, 337, 362, 397, 413, 429, 452, 456, 460, 535, 542, 567, 574, 587, 608, 615, 636, 664, 686, 702, 770, 787, 795, 804, 889, 902, 954], 'Health Care': [5, 6, 12, 21, 22, 33, 39, 46, 52, 55, 63, 72, 79, 86, 123, 124, 125, 130, 138, 140, 141, 168, 172, 200, 201, 202, 263, 268, 278, 286, 287, 290, 291, 305, 325, 358, 359, 372, 420, 430, 431, 447, 457, 465, 469, 515, 527, 537, 553, 559, 583, 618, 629, 661, 684, 693, 697, 708, 746, 749, 766, 775, 790, 799, 815, 818, 845, 868, 881, 883, 935, 960, 965, 977, 978], 'Hotels, Resturants & Leisure': [109, 146, 195, 218, 241, 254, 309, 371, 444, 466, 534, 546, 557, 562, 585, 731, 763, 764, 779, 797, 895, 915, 918, 941, 999], 'Household Products': [34, 151, 174, 256, 261, 328, 338, 345, 370, 434, 441, 450, 455, 533, 550, 554, 601, 665, 699, 716, 856, 890, 900, 907, 932, 950, 967, 992], 'Industrials': [11, 59, 75, 93, 97, 128, 134, 148, 211, 224, 360, 377, 396, 412, 419, 539, 544, 596, 622, 623, 630, 645, 655, 658, 666, 674, 690, 757, 782, 789, 806, 813, 823, 831, 832, 835, 841, 847, 866, 867, 873, 887, 942, 947, 964, 1000], 'Materials': [126, 127, 170, 244, 251, 303, 321, 341, 356, 373, 375, 383, 417, 418, 426, 435, 446, 480, 489, 514, 518, 577, 586, 616, 617, 620, 625, 628, 637, 639, 641, 660, 667, 687, 691, 751, 774, 793, 857, 885, 911, 982, 986], 'Media': [53, 96, 99, 203, 213, 255, 327, 366, 406, 414, 525, 530, 681, 705, 707, 722, 741, 752, 759, 762, 821, 913, 968, 969, 989], 'Motor Vehicles & Parts': [8, 9, 70, 147, 154, 169, 281, 310, 334, 339, 424, 428, 470, 588, 591, 604, 647, 670, 718, 739, 811, 957, 961, 979], 'Retailing': [1, 15, 28, 38, 47, 71, 89, 103, 111, 132, 136, 139, 143, 145, 177, 180, 191, 196, 197, 228, 234, 237, 238, 240, 258, 267, 269, 280, 293, 297, 299, 302, 330, 342, 346, 361, 365, 374, 379, 380, 393, 415, 427, 439, 495, 500, 502, 511, 512, 517, 523, 582, 592, 602, 607, 610, 621, 643, 644, 648, 657, 675, 689, 721, 748, 771, 773, 807, 812, 824, 825, 827, 840, 876, 894, 899, 922, 937, 940, 973], 'Technology': [3, 18, 20, 25, 31, 36, 51, 54, 77, 110, 113, 133, 150, 157, 158, 164, 173, 194, 219, 220, 230, 233, 284, 295, 300, 308, 313, 331, 385, 386, 400, 408, 409, 422, 451, 462, 464, 487, 491, 504, 505, 508, 513, 519, 524, 532, 543, 552, 563, 565, 584, 589, 593, 594, 612, 632, 634, 638, 649, 659, 673, 676, 678, 682, 688, 700, 725, 733, 736, 753, 760, 769, 778, 805, 830, 834, 842, 854, 864, 871, 888, 891, 893, 896, 904, 905, 906, 909, 912, 914, 919, 927, 931, 943, 944, 946, 956, 970, 971, 975, ...], 'Telecommunications': [10, 13, 37, 116, 159, 187, 292, 333, 399, 443, 461, 496, 526, 619, 786], 'Transportation': [48, 58, 67, 68, 80, 129, 142, 208, 239, 270, 353, 390, 395, 405, 407, 416, 432, 459, 521, 528, 570, 578, 642, 672, 709, 713, 740, 800, 814, 858, 884, 930, 933, 945, 972, 974], 'Wholesalers': [57, 64, 92, 102, 108, 119, 122, 167, 183, 185, 212, 276, 285, 315, 317, 320, 323, 335, 351, 357, 369, 391, 423, 463, 474, 477, 484, 564, 581, 599, 627, 653, 685, 727, 747, 780, 808, 837, 875, 991]}

In [8]:
fortune.loc[24,]

Company                     Boeing
Sector         Aerospace & Defense
Industry     Aerospace and Defense
Location               Chicago, IL
Revenue                      96114
Profits                       5176
Employees                   161400
Name: 24, dtype: object

In [9]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [10]:
sectors.get_group("Energy")
sectors.get_group("Technology")

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
18,Amazon.com,Technology,Internet Services and Retailing,"Seattle, WA",107006,596,230800
20,HP,Technology,"Computers, Office Equipment","Palo Alto, CA",103355,4554,287000
25,Microsoft,Technology,Computer Software,"Redmond, WA",93580,12193,118000
31,IBM,Technology,Information Technology Services,"Armonk, NY",82461,13190,411798
...,...,...,...,...,...,...,...
970,Rackspace Hosting,Technology,Internet Services and Retailing,"San Antonio, TX",2001,126,6189
971,VeriFone Systems,Technology,"Computers, Office Equipment","San Jose, CA",2001,79,5400
975,Super Micro Computer,Technology,"Computers, Office Equipment","San Jose, CA",1991,102,2285
984,Nuance Communications,Technology,Computer Software,"Burlington, MA",1931,-115,13500
990,F5 Networks,Technology,Network and Other Communications Equipment,"Seattle, WA",1920,365,4178

In [11]:
sectors.max()
sectors.min()
sectors.sum()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,BoeingUnited TechnologiesLockheed MartinGenera...,Aerospace and DefenseAerospace and DefenseAero...,"Chicago, ILFarmington, CTBethesda, MDFalls Chu...",357940,28742,968057
Apparel,NikeVFPVHRalph LaurenHanesbrandsLevi StraussCo...,ApparelApparelApparelApparelApparelApparelAppa...,"Beaverton, ORGreensboro, NCNew York, NYNew Yor...",95968,8236,346397
Business Services,ManpowerGroupOmnicom GroupAramarkVisaWaste Man...,"Temporary HelpAdvertising, marketingDiversifie...","Milwaukee, WINew York, NYPhiladelphia, PAFoste...",272195,28227,1361050
Chemicals,Dow ChemicalDuPontPPG IndustriesMonsantoEcolab...,ChemicalsChemicalsChemicalsChemicalsChemicalsC...,"Midland, MIWilmington, DEPittsburgh, PASt. Lou...",243897,22628,463651
Energy,Exxon MobilChevronPhillips 66Valero EnergyMara...,Petroleum RefiningPetroleum RefiningPetroleum ...,"Irving, TXSan Ramon, CAHouston, TXSan Antonio,...",1517809,-73447,1188927
Engineering & Construction,FluorAECOMJacobs Engineering GroupD.R. HortonL...,"Engineering, ConstructionEngineering, Construc...","Irving, TXLos Angeles, CAPasadena, CAFort Wort...",153983,5304,406708
Financials,Berkshire HathawayFannie MaeJ.P. Morgan ChaseB...,Insurance: Property and Casualty (Stock)Divers...,"Omaha, NEWashington, DCNew York, NYCharlotte, ...",2217159,260209,3359948
Food and Drug Stores,CVS HealthKrogerWalgreens Boots AlliancePublix...,Food and Drug StoresFood and Drug StoresFood a...,"Woonsocket, RICincinnati, OHDeerfield, ILLakel...",483769,16759,1395398
"Food, Beverages & Tobacco",Archer Daniels MidlandPepsiCoCoca-ColaTyson Fo...,Food ProductionFood Consumer ProductsBeverages...,"Chicago, ILPurchase, NYAtlanta, GASpringdale, ...",555967,51417,1211632
Health Care,McKessonUnitedHealth GroupAmerisourceBergenCar...,Wholesalers: Health CareHealth Care: Insurance...,"San Francisco, CAMinnetonka, MNChesterbrook, P...",1614707,106114,2678289
"Hotels, Resturants & Leisure",McDonald’sStarbucksMarriott InternationalYum B...,"Food ServicesFood ServicesHotels, Casinos, Res...","Oak Brook, ILSeattle, WABethesda, MDLouisville...",169546,20697,2484245
Household Products,Procter & GambleKimberly-ClarkColgate-Palmoliv...,Household and Personal ProductsHousehold and P...,"Cincinnati, OHIrving, TXNew York, NYNew Britai...",234737,14428,646038
Industrials,General ElectricCaterpillarHoneywell Internati...,Industrial MachineryConstruction and Farm Mach...,"Fairfield, CTPeoria, ILMorris Plains, NJSt. Pa...",497581,20764,1545229
Materials,AlcoaInternational PaperNucorUnited States Ste...,"MetalsPackaging, ContainersMetalsMetalsPackagi...","New York, NYMemphis, TNCharlotte, NCPittsburgh...",259145,4428,638123
Media,DisneyTwenty-First Century FoxTime WarnerCBSVi...,EntertainmentEntertainmentEntertainmentEnterta...,"Burbank, CANew York, NYNew York, NYNew York, N...",220764,24347,550314
Motor Vehicles & Parts,General MotorsFord MotorJohnson ControlsPaccar...,Motor Vehicles and PartsMotor Vehicles and Par...,"Detroit, MIDearborn, MIMilwaukee, WIBellevue, ...",482540,25898,1082560
Retailing,WalmartCostcoHome DepotTargetLowe’sBest BuyTJX...,General MerchandisersSpecialty Retailers: Othe...,"Bentonville, ARIssaquah, WAAtlanta, GAMinneapo...",1465076,47830,6227629
Technology,AppleAmazon.comHPMicrosoftIBMAlphabetIntelCisc...,"Computers, Office EquipmentInternet Services a...","Cupertino, CASeattle, WAPalo Alto, CARedmond, ...",1377600,180473,3578949
Telecommunications,AT&TVerizonComcastTime Warner CableCenturyLink...,TelecommunicationsTelecommunicationsTelecommun...,"Dallas, TXNew York, NYPhiladelphia, PANew York...",461834,48637,832468
Transportation,UPSFedExAmerican Airlines GroupDelta Air Lines...,"Mail, Package, and Freight DeliveryMail, Packa...","Atlanta, GAMemphis, TNFort Worth, TXAtlanta, G...",408508,44169,1536793
Wholesalers,SyscoIngram MicroWorld Fuel ServicesAvnetTech ...,Wholesalers: Food and GroceryWholesalers: Elec...,"Houston, TXIrvine, CAMiami, FLPhoenix, AZClear...",444800,8233,525597

In [12]:
sectors.get_group("Apparel")["Profits"].sum()

np.int64(8236)

In [13]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby(["Sector","Industry"])
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [14]:
sectors.sum()

                                                                                                             Company  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                          BoeingUnited TechnologiesLockheed MartinGenera...
Apparel             Apparel                                        NikeVFPVHRalph LaurenHanesbrandsLevi StraussCo...
Business Services   Advertising, marketing                                            Omnicom GroupInterpublic Group
                    Diversified Outsourcing Services               AramarkADPABM IndustriesCintasTowers WatsonADT...
                    Education                                      Graham HoldingsApollo Education GroupDeVry Edu...
...                                                                                                              ...
Transportation      Trucking, Truck Leasing                        Ryder SystemJ.B. Hunt Transport ServicesYRC Wo...
Wholesalers         Miscellaneous                                                                             Univar
                    Wholesalers: Diversified                       World Fuel ServicesNGL Energy PartnersGenuine ...
                    Wholesalers: Electronics and Office Equipment  Ingram MicroAvnetTech DataArrow ElectronicsSyn...
                    Wholesalers: Food and Grocery                  SyscoUS Foods HoldingPerformance Food GroupCor...

                                                                                                            Location  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                          Chicago, ILFarmington, CTBethesda, MDFalls Chu...
Apparel             Apparel                                        Beaverton, ORGreensboro, NCNew York, NYNew Yor...
Business Services   Advertising, marketing                                                  New York, NYNew York, NY
                    Diversified Outsourcing Services               Philadelphia, PARoseland, NJNew York, NYCincin...
                    Education                                              Arlington, VAPhoenix, AZDowners Grove, IL
...                                                                                                              ...
Transportation      Trucking, Truck Leasing                        Miami, FLLowell, AROverland Park, KSPhoenix, A...
Wholesalers         Miscellaneous                                                                  Downers Grove, IL
                    Wholesalers: Diversified                       Miami, FLTulsa, OKAtlanta, GAWaltham, MALake F...
                    Wholesalers: Electronics and Office Equipment  Irvine, CAPhoenix, AZClearwater, FLCentennial,...
                    Wholesalers: Food and Grocery                  Houston, TXRosemont, ILRichmond, VASouth San F...

                                                                   Revenue  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                           357940
Apparel             Apparel                                          95968
Business Services   Advertising, marketing                           22748
                    Diversified Outsourcing Services                 64829
                    Education                                         7485
...                                                                    ...
Transportation      Trucking, Truck Leasing                          35950
Wholesalers         Miscellaneous                                     8982
                    Wholesalers: Diversified                        176138
                    Wholesalers: Electronics and Office Equipment   147906
                    Wholesalers: Food and Grocery                   111774

                                                                   Profits  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                            28742
Apparel             Apparel                                           8236
Business Services   Advertising, marketing                            1549
                    Diversified Outsourcing Services                  4305
                    Education                                           69
...                                                                    ...
Transportation      Trucking, Truck Leasing                           1910
Wholesalers         Miscellaneous                                       17
                    Wholesalers: Diversified                          5193
                    Wholesalers: Electronics and Office Equipment     1857
                    Wholesalers: Food and Grocery                     1166

                                                                   Employees
Sector              Industry
Aerospace & Defense Aerospace and Defense                             968057
Apparel             Apparel                                           346397
Business Services   Advertising, marketing                            124100
                    Diversified Outsourcing Services                  708330
                    Education                                          46755
...                                                                      ...
Transportation      Trucking, Truck Leasing                           170456
Wholesalers         Miscellaneous                                       9200
                    Wholesalers: Diversified                          233831
                    Wholesalers: Electronics and Office Equipment     166661
                    Wholesalers: Food and Grocery                     115905

[79 rows x 5 columns]

In [15]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [16]:
sectors.agg({"Revenue":"sum",
            "Profits":"sum",
            "Employees":"mean"})

                              Revenue  Profits     Employees
Sector
Aerospace & Defense            357940    28742  48402.850000
Apparel                         95968     8236  23093.133333
Business Services              272195    28227  26687.254902
Chemicals                      243897    22628  15455.033333
Energy                        1517809   -73447   9745.303279
Engineering & Construction     153983     5304  15642.615385
Financials                    2217159   260209  24172.287770
Food and Drug Stores           483769    16759  93026.533333
Food, Beverages & Tobacco      555967    51417  28177.488372
Health Care                   1614707   106114  35710.520000
Hotels, Resturants & Leisure   169546    20697  99369.800000
Household Products             234737    14428  23072.785714
Industrials                    497581    20764  33591.934783
Materials                      259145     4428  14840.069767
Media                          220764    24347  22012.560000
Motor Vehicles & Parts         482540    25898  45106.666667
Retailing                     1465076    47830  77845.362500
Technology                    1377600   180473  35087.735294
Telecommunications             461834    48637  55497.866667
Transportation                 408508    44169  42688.694444
Wholesalers                    444800     8233  13139.925000

In [17]:
df = pd.DataFrame(columns= fortune.columns)

In [18]:
for sector, data in sectors:
    highest_revenue = data.nlargest(1, "Revenue")
    df = df.append(highest_revenue)

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
41,Archer Daniels Midland,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",67702,1849,32300
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
109,McDonald’s,"Hotels, Resturants & Leisure",Food Services,"Oak Brook, IL",25413,4529,420000
34,Procter & Gamble,Household Products,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
11,General Electric,Industrials,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
126,Alcoa,Materials,Metals,"New York, NY",22534,-322,60000
53,Disney,Media,Entertainment,"Burbank, CA",52465,8382,185000
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
48,UPS,Transportation,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
57,Sysco,Wholesalers,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [ ]:

cities = fortune.groupby("Location")

In [ ]:
for sector, data in cities:
    highest_revenue = data.nlargest(1, "Revenue")
    df = df.append(highest_revenue)

In [ ]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
41,Archer Daniels Midland,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",67702,1849,32300
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
109,McDonald’s,"Hotels, Resturants & Leisure",Food Services,"Oak Brook, IL",25413,4529,420000
34,Procter & Gamble,Household Products,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
11,General Electric,Industrials,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
126,Alcoa,Materials,Metals,"New York, NY",22534,-322,60000
53,Disney,Media,Entertainment,"Burbank, CA",52465,8382,185000
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
48,UPS,Transportation,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
57,Sysco,Wholesalers,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
41,Archer Daniels Midland,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",67702,1849,32300
...,...,...,...,...,...,...,...
120,Raytheon,Aerospace & Defense,Aerospace and Defense,"Waltham, MA",23247,2074,61000
850,United Refining,Energy,Petroleum Refining,"Warren, PA",2470,82,2997
431,Zimmer Biomet Holdings,Health Care,Medical Products and Equipment,"Warsaw, IN",5998,147,17500
16,Fannie Mae,Financials,Diversified Financials,"Washington, DC",110359,10954,7300
542,Keurig Green Mountain,"Food, Beverages & Tobacco",Beverages,"Waterbury, VT",4520,498,6000
898,MPM Holdings,Chemicals,Chemicals,"Waterford, NY",2289,-83,5000
874,Granite Construction,Engineering & Construction,"Engineering, Construction","Watsonville, CA",2371,61,3200
1000,Briggs & Stratton,Industrials,Industrial Machinery,"Wauwatosa, WI",1895,46,5480
240,Toys “R” Us,Retailing,Specialty Retailers: Other,"Wayne, NJ",11802,-130,62000
785,B/E Aerospace,Aerospace & Defense,Aerospace and Defense,"Wellington, FL",2730,286,10057
383,AK Steel Holding,Materials,Metals,"West Chester, OH",6693,-509,8500
829,Platform Specialty Products,Chemicals,Chemicals,"West Palm Beach, FL",2542,-309,8200
996,New York Community Bancorp,Financials,Commercial Banks,"Westbury, NY",1902,-47,3448
456,Ingredion,"Food, Beverages & Tobacco",Food Production,"Westchester, IL",5621,402,11500
439,TravelCenters of America,Retailing,Specialty Retailers: Other,"Westlake, OH",5851,28,18450
396,Terex,Industrials,Construction and Farm Machinery,"Westport, CT",6543,146,20400
847,ITT,Industrials,Industrial Machinery,"White Plains, NY",2486,352,9700
389,Spirit AeroSystems Holdings,Aerospace & Defense,Aerospace and Defense,"Wichita, KS",6644,789,15200
849,Tops Holding,Food and Drug Stores,Food and Drug Stores,"Williamsville, NY",2472,-62,14800
674,Westinghouse Air Brake Technologies,Industrials,Industrial Machinery,"Wilmerding, PA",3308,399,13000
101,DuPont,Chemicals,Chemicals,"Wilmington, DE",27940,1953,52000
607,Fastenal,Retailing,Specialty Retailers: Other,"Winona, MN",3869,516,20746
266,Reynolds American,"Food, Beverages & Tobacco",Tobacco,"Winston-Salem, NC",10675,3253,5650
678,Skyworks Solutions,Technology,Semiconductors and Other Electronic Components,"Woburn, MA",3258,798,6700
172,Health Net,Health Care,Health Care: Insurance and Managed Care,"Woodland Hills, CA",16244,186,8584
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
506,Hanover Insurance Group,Financials,Insurance: Property and Casualty (Stock),"Worcester, MA",5034,332,4800
764,Penn National Gaming,"Hotels, Resturants & Leisure","Hotels, Casinos, Resorts","Wyomissing, PA",2838,1,18204
773,Bon-Ton Stores,Retailing,General Merchandisers,"York, PA",2790,-57,24100
932,Herman Miller,Household Products,"Home Equipment, Furnishings","Zeeland, MI",2142,98,7510